### ISSUE TITLE
error testing the component

### ISSUE THREAD

**Issue by rambambulli** [oscarmarinmiro/aframe-stereo-component#16]
Hi guys,

I wanted to give a-frame a try this weekend. I'm a javascript noob so it looked good for me. I love it so far.

So I wanted to give this component a try.
I used the code from the red and blue example and copied the files from the dist folder to my web server.

When I open the index.html in Chrome I get the error:

_Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty._

What have I done wrong?

Btw, If I use the build.js from the example folder it works fine.

thanks!

( I'm a newbie on this so I hope I don't ask a very stupid question here.)

**Comment by Runnermax** [comment]
Hey! Thank you for this message, same problem here. Thought i was going insane with this problem over the last few days. Tried everything, the component is broken somehow. Probably after some changes to the aframe master, as this component hasn't been updatet for a few month now.
I really hope anyone with coding experience reads this. Would love to have some stereo pictures in aframe. :D
