### ISSUE TITLE
Ability to view over and under videos

### ISSUE THREAD

**Issue by qster123** [oscarmarinmiro/aframe-stereo-component#8]
Hi, how could this be modified to play over and under videos?

**Comment by oscarmarinmiro** [comment]
Hi Lee,

I'm on vacation with only phone access, but in like 10 days I'll add this
functionality, I also think is much needed.

**Comment by masterofshapes** [comment]
Any update on this? Also curious about if I could use over under videos

**Comment by oscarmarinmiro** [comment]
This was done by @dlochrie and integrated into 'master' branch a few days ago. Also, there's a new release here https://github.com/oscarmarinmiro/aframe-stereo-component/releases/tag/v0.3.0 , that works with over/under (howto in the README :) ) and aframe ^0.3.0

**Comment by theDrGray** [comment]
This is working well, but the eyes are inverted. Top is going to right eye and vice versa.

**Comment by qster123** [comment]
I'm also seeing the eyes inverted for O&U videos, but great job on this :)

**Comment by oscarmarinmiro** [comment]
Ughhh.. sorry.

Now corrected in master and new release https://github.com/oscarmarinmiro/aframe-stereo-component/releases/tag/v0.3.1
